version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/etc:/etc/nginx
      - ./ssl:/etc/ssl
    networks:
      - nginx-network

networks:
  nginx-network:
    driver: bridge
