version: "3"
services:
  influxdb:
    image: influxdb:2.7.1
    container_name: influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=inituser
      - DOCKER_INFLUXDB_INIT_PASSWORD=initpass
      - DOCKER_INFLUXDB_INIT_ORG=first-org
      - DOCKER_INFLUXDB_INIT_BUCKET=telegraf
    volumes:
      - ./influxdb/data:/var/lib/influxdb2
      - ./influxdb/config:/etc/influxdb2
    ports:
      - 8086:8086
    restart: unless-stopped
    networks:
      - tig_network
 
  telegraf:
    image: telegraf:1.26.3
    hostname: networkmetrics
    container_name: telegraf
    user: "0"
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
      - ./telegraf/telegraf.d:/etc/telegraf/telegraf.d
      - /usr/share/snmp/mibs:/usr/share/snmp/mibs
      - /usr/share/snmp/mibs/iana:/usr/share/snmp/mibs/iana
      - /usr/share/snmp/mibs/ietf:/usr/share/snmp/mibs/ietf
    restart: unless-stopped
    networks:
      - tig_network
 
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    user: '0'
    ports:
      - 3000:3000
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/config:/etc/grafana
      - ./grafana/log:/var/log/grafana
    restart: unless-stopped
    networks:
      - tig_network
 
networks:
  tig_network:
    driver: bridge
